db_host: "localhost"
db_port: 5432
db_name: "mateamt"
db_user: "mateamt"
db_passwd: "mateamt"
listen_port: 8000
#listen_host: "127.0.0.1"
#max_connections_per_client: 10
currency: "€"
block_registration: false
